/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.afip.dgi.agencia66.tramites.view;

import gov.afip.dgi.agencia66.model.Agentes;
import gov.afip.dgi.agencia66.model.ControladorFiscal;
import gov.afip.dgi.agencia66.model.ParCaracter;
import gov.afip.dgi.agencia66.model.Tramites;
import gov.afip.dgi.agencia66.controller.ControladorFiscalJpaController;
import gov.afip.dgi.agencia66.controller.EntityMan;
import gov.afip.dgi.agencia66.exceptions.ValidacionObjetoException;
import gov.afip.dgi.agencia66.tramites.controller.LecturaDeArchivos;
import gov.afip.dgi.agencia66.tramites.controller.LoaderDeInicio;
import gov.afip.dgi.agencia66.tramites.util.ImprimeActaAnexoCF;
import gov.afip.dgi.agencia66.util.FormateaSalidasTexto;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.Calendar;
import java.util.logging.LogManager;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;

/**
 *
 * @author u84062
 */
public class LeerControladorFiscal extends javax.swing.JFrame {
    private final static Logger LOGGER = Logger.getLogger("gov.afip.dgi.agencia66.tramites.view");
    File fichero;
    String rutaArchivo;
    private List listaAgentes = null; 
    private final ControladorFiscal controlador = new ControladorFiscal();
    LecturaDeArchivos leyendo = new LecturaDeArchivos();
    private static LeerControladorFiscal lcf;
    private final List<String> errores = new ArrayList<String>();
    private int ind_aux = 0;
    
    FormateaSalidasTexto fst = new FormateaSalidasTexto();
    
    public LeerControladorFiscal() throws javax.persistence.PersistenceException {
        LOGGER.log(Level.INFO, "Leer ControladorFiscal");
        initComponents();
        URL url = getClass().getResource("/gov/afip/dgi/agencia66/tramites/view/icono.png");
        ImageIcon icono = new ImageIcon(url);
        setIconImage(icono.getImage());
        completarPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        lblTitulo = new javax.swing.JLabel();
        sprTitulo = new javax.swing.JSeparator();
        lblOperador = new javax.swing.JLabel();
        cmbOperador = new javax.swing.JComboBox<>();
        txtLegajo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtArchivo = new javax.swing.JTextField();
        btnLeerArchivo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnElegirArchivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSolicitud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtActa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCuit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbCaracter = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPuestoVta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBloqueos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtPrecinto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbTramite = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTecnico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCredencial = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btnProcesar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblZ = new javax.swing.JLabel();
        txtZ = new javax.swing.JTextField();
        lblInterAfip = new javax.swing.JLabel();
        txtInterAfip = new javax.swing.JTextField();
        lvlPaginaAfip = new javax.swing.JLabel();
        txtPaginaAfip = new javax.swing.JTextField();
        lblInterTec = new javax.swing.JLabel();
        txtInterTec = new javax.swing.JTextField();
        lblPagTec = new javax.swing.JLabel();
        txtPagTec = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblVentaDiaria = new javax.swing.JLabel();
        txtVentaDiaria = new javax.swing.JTextField();
        txtIvaDiario = new javax.swing.JTextField();
        txtCptoNoGravado = new javax.swing.JTextField();
        lblIvaDiario = new javax.swing.JLabel();
        lblCptosNoGravados = new javax.swing.JLabel();
        lblUltimoB = new javax.swing.JLabel();
        txtUltimoB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUltimoA = new javax.swing.JTextField();
        optLogo = new javax.swing.JCheckBox();
        optSerie = new javax.swing.JCheckBox();
        optFecha = new javax.swing.JCheckBox();
        optUltimoZ = new javax.swing.JCheckBox();
        optExtDatos = new javax.swing.JCheckBox();
        optCompAuditoria = new javax.swing.JCheckBox();
        optBloqueo = new javax.swing.JCheckBox();
        optTktBloqueo = new javax.swing.JCheckBox();
        optIntervinoLur = new javax.swing.JCheckBox();
        optBloqueosLur = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtPrecinto445 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrecintoLur = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        txtObservaciones1 = new javax.swing.JTextField();
        lvlObservaciones1 = new javax.swing.JLabel();
        txtObservaciones2 = new javax.swing.JTextField();
        btnLimpiaPantalla = new javax.swing.JButton();
        optOperativo = new javax.swing.JCheckBox();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 153, 153));

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/afip/dgi/agencia66/tramites/view/view/leer.png"))); // NOI18N
        lblTitulo.setText("LECTURA DE CONTROLADORES FISCALES");

        lblOperador.setText("Agente operador: ");

        cmbOperador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un operador" }));
        cmbOperador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOperadorItemStateChanged(evt);
            }
        });
        cmbOperador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbOperadorFocusLost(evt);
            }
        });
        cmbOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperadorActionPerformed(evt);
            }
        });

        txtLegajo.setEditable(false);
        txtLegajo.setBackground(new java.awt.Color(153, 153, 153));
        txtLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLegajoActionPerformed(evt);
            }
        });

        jLabel1.setText("Legajo: ");

        btnLeerArchivo.setText("Leer Archivo");
        btnLeerArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerArchivoActionPerformed(evt);
            }
        });

        btnElegirArchivo.setText("Elegir Archivo a procesar");
        btnElegirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirArchivoActionPerformed(evt);
            }
        });

        jLabel2.setText("N° Solicitud: ");

        txtSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolicitudActionPerformed(evt);
            }
        });

        jLabel3.setText("N° Acta:");

        jLabel4.setText("CUIT:");

        txtCuit.setEditable(false);
        txtCuit.setBackground(new java.awt.Color(153, 153, 153));
        txtCuit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCuitFocusLost(evt);
            }
        });
        txtCuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuitActionPerformed(evt);
            }
        });

        jLabel5.setText("Razon Social: ");

        txtRazonSocial.setEditable(false);
        txtRazonSocial.setBackground(new java.awt.Color(153, 153, 153));
        txtRazonSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazonSocialFocusLost(evt);
            }
        });
        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre: ");

        jLabel7.setText("Documento:");

        jLabel8.setText("Telefono:");

        jLabel9.setText("Direccion: ");

        jLabel10.setText("Carácter:");

        cmbCaracter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));

        lblMarca.setText("Marca:");

        lblModelo.setText("Modelo");

        lblCodigo.setText("Código:");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(153, 153, 153));

        jLabel14.setText("Puesto de Venta:");

        txtPuestoVta.setEditable(false);
        txtPuestoVta.setBackground(new java.awt.Color(153, 153, 153));

        jLabel15.setText("Bloqueos:");

        txtBloqueos.setEditable(false);
        txtBloqueos.setBackground(new java.awt.Color(153, 153, 153));

        jLabel16.setText("Precinto CF:");

        txtPrecinto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecintoFocusLost(evt);
            }
        });
        txtPrecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecintoActionPerformed(evt);
            }
        });

        jLabel17.setText("Trámite:");

        cmbTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un trámite" }));
        cmbTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTramiteActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel18.setText("Sólo para casos de apertura por técnico autorizado");

        jLabel19.setText("Nombre:");

        jLabel20.setText("Credencial N°:");

        btnProcesar.setBackground(new java.awt.Color(0, 0, 255));
        btnProcesar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProcesar.setForeground(new java.awt.Color(255, 255, 255));
        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblZ.setText("Comprobante Z:");

        txtZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZActionPerformed(evt);
            }
        });

        lblInterAfip.setText("Inter. AFIP:");

        lvlPaginaAfip.setText("Pág.:");

        txtPaginaAfip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginaAfipActionPerformed(evt);
            }
        });

        lblInterTec.setText("Inter. Técnico:");

        lblPagTec.setText("Pág.:");

        lblNumero.setText("Número:");

        txtNumero.setEditable(false);
        txtNumero.setBackground(new java.awt.Color(153, 153, 153));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lblVentaDiaria.setText("Venta Diaria:");

        txtCptoNoGravado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCptoNoGravadoActionPerformed(evt);
            }
        });

        lblIvaDiario.setText("IVA Diario");

        lblCptosNoGravados.setText("Conceptos No Gravados");

        lblUltimoB.setText("Último B/C:");

        jLabel12.setText("Último A:");

        optLogo.setSelected(true);
        optLogo.setText("Logotipo Ok");

        optSerie.setSelected(true);
        optSerie.setText("N° Serie Ok");

        optFecha.setSelected(true);
        optFecha.setText("Fecha Ok");

        optUltimoZ.setSelected(true);
        optUltimoZ.setText("Último Z");
        optUltimoZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optUltimoZActionPerformed(evt);
            }
        });

        optExtDatos.setSelected(true);
        optExtDatos.setText("Ext. Datos");

        optCompAuditoria.setSelected(true);
        optCompAuditoria.setText("Comp Auditoria");

        optBloqueo.setSelected(true);
        optBloqueo.setText("Bloqueo CF");

        optTktBloqueo.setSelected(true);
        optTktBloqueo.setText("Ticket Bloqueo");

        optIntervinoLur.setSelected(true);
        optIntervinoLur.setText("Intervino LUR");

        optBloqueosLur.setSelected(true);
        optBloqueosLur.setText("Coinciden Bloqueos con LUR");
        optBloqueosLur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBloqueosLurActionPerformed(evt);
            }
        });

        jLabel11.setText("Precinto en F445");

        txtPrecinto445.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecinto445ActionPerformed(evt);
            }
        });

        jLabel13.setText("Precinto LUR");

        jLabel21.setBackground(java.awt.Color.white);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/afip/dgi/agencia66/tramites/view/afip.png"))); // NOI18N

        lblObservaciones.setText("Observaciones:");

        lvlObservaciones1.setText("Observaciones del Tecnico:");

        txtObservaciones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObservaciones2ActionPerformed(evt);
            }
        });

        btnLimpiaPantalla.setText("Limpiar Pantalla");
        btnLimpiaPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaPantallaActionPerformed(evt);
            }
        });

        optOperativo.setSelected(true);
        optOperativo.setText("Operativo");
        optOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optOperativoActionPerformed(evt);
            }
        });

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUENO", "REGULAR", "MALO" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/afip/dgi/agencia66/tramites/view/view/controlaIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sprTitulo)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblObservaciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObservaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecinto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecinto445, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecintoLur, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtActa, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jSeparator6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cmbCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtDireccion)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnElegirArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLeerArchivo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUltimoB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(optExtDatos)
                                                .addGap(18, 18, 18)
                                                .addComponent(optCompAuditoria)
                                                .addGap(18, 18, 18)
                                                .addComponent(optBloqueo)
                                                .addGap(18, 18, 18)
                                                .addComponent(optTktBloqueo)
                                                .addGap(18, 18, 18)
                                                .addComponent(optIntervinoLur)
                                                .addGap(18, 18, 18)
                                                .addComponent(optBloqueosLur))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtUltimoB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblInterAfip)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtInterAfip, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(txtPaginaAfip, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(lvlPaginaAfip))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblInterTec)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtInterTec, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblPagTec)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtPagTec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtUltimoA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(optOperativo)
                                                        .addGap(221, 221, 221)))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMarca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblModelo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPuestoVta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(lblOperador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(lblZ)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblVentaDiaria)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVentaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(lblIvaDiario)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(optUltimoZ)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(optLogo)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(optSerie)
                                                    .addGap(10, 10, 10)
                                                    .addComponent(optFecha))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtIvaDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblCptosNoGravados)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCptoNoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel22)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(jLabel21)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnProcesar)
                        .addGap(138, 138, 138)
                        .addComponent(jButton2)
                        .addGap(99, 99, 99)
                        .addComponent(btnLimpiaPantalla)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lvlObservaciones1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtObservaciones2)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sprTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperador)
                    .addComponent(cmbOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17)
                    .addComponent(cmbTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeerArchivo)
                    .addComponent(btnElegirArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMarca)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblModelo)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCodigo)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumero)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPuestoVta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtBloqueos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblZ)
                        .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblVentaDiaria)
                        .addComponent(txtVentaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIvaDiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCptoNoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblIvaDiario)
                        .addComponent(lblCptosNoGravados)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltimoB)
                    .addComponent(txtUltimoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtUltimoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optLogo)
                    .addComponent(optSerie)
                    .addComponent(optFecha)
                    .addComponent(optUltimoZ)
                    .addComponent(optOperativo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optBloqueo)
                    .addComponent(optIntervinoLur)
                    .addComponent(optBloqueosLur)
                    .addComponent(optTktBloqueo)
                    .addComponent(optExtDatos)
                    .addComponent(optCompAuditoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPagTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInterAfip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlPaginaAfip)
                    .addComponent(txtPaginaAfip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInterAfip)
                    .addComponent(lblInterTec)
                    .addComponent(txtInterTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagTec)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPrecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrecinto445, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtPrecintoLur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtActa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObservaciones)
                    .addComponent(txtObservaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObservaciones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lvlObservaciones1))
                .addGap(15, 15, 15)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpiaPantalla)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLegajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLegajoActionPerformed

    private void btnElegirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser("J:\\");
        int seleccion  = fileChooser.showOpenDialog(this);

        if(seleccion == fileChooser.APPROVE_OPTION) {
            //Seleccionamos el fichero
            File fichero = fileChooser.getSelectedFile();

            //Ecribe la ruta del fichero seleccionado en el campo de texto
            rutaArchivo = fichero.getAbsolutePath();
            txtArchivo.setText(rutaArchivo);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnElegirArchivoActionPerformed

    private void btnLeerArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerArchivoActionPerformed
        LOGGER.log(Level.INFO, "Leer Archivo");
        
        if(txtArchivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un archivo" +mensajesDeError(), "Errores de Validación", JOptionPane.ERROR_MESSAGE );
        } else {
            //FormateaSalidasTexto fst = new FormateaSalidasTexto();
            leyendo.leerArchivo(rutaArchivo);
            txtCuit.setText(fst.formatoCuit(leyendo.getCuit()));
            txtRazonSocial.setText(leyendo.getRazon_social());
            completaNombre();
            
            txtDocumento.setText(leyendo.getDocumento());
            txtCodigo.setText(leyendo.getCodigo());
            txtPuestoVta.setText(Integer.toString(leyendo.getPtoVta()));
            txtBloqueos.setText(Integer.toString(leyendo.getBloqueo()));
            completaDocumento();
            txtNumero.setText(leyendo.getNumero());
        }
    }//GEN-LAST:event_btnLeerArchivoActionPerformed

    private void cmbOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOperadorActionPerformed

    private void cmbOperadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOperadorItemStateChanged
        String agenteSelected;
        Agentes a_gente;
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            agenteSelected = (String)cmbOperador.getSelectedItem();
            //System.out.println("Es: " +agenteSelected);
            for(int i=0; i<listaAgentes.size(); i++) {
                a_gente = (Agentes) listaAgentes.get(i);
                if(agenteSelected.equals(a_gente.getNombre())){
                    txtLegajo.setText(a_gente.getLegajo());
                    break;
                }
                else { txtLegajo.setText(null);}
            }
        }
        
        
    }//GEN-LAST:event_cmbOperadorItemStateChanged

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        completaNombre();
        completaDocumento();
    }//GEN-LAST:event_txtRazonSocialActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed

        LOGGER.log(Level.INFO, "Porocesando informacion");
        ControladorFiscal cf = null;
        try {
            cf = generaObjetoCF();
            grabarTramite(cf);
            limpiarPantalla();
        } catch (ValidacionObjetoException ex) {
       //   catch (Exception ex) {  
            JOptionPane.showMessageDialog(this, "Solucione los siguientes errores: " +mensajesDeError(), "Errores de Validación", JOptionPane.ERROR_MESSAGE );
       //     JOptionPane.showMessageDialog(this, "Solucione los siguientes errores!: " +ex.getMessage(), "Errores de Validación", JOptionPane.ERROR_MESSAGE);
       //     ex.printStackTrace();
        }
        

/*            System.out.println("En mi Catch");
            Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Solucione los siguientes errores: " +mensajesDeError(), "Errores de Validación", JOptionPane.ERROR_MESSAGE ); 
  */        
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void txtPaginaAfipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginaAfipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginaAfipActionPerformed

    private void cmbTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTramiteActionPerformed
        int indice = cmbTramite.getSelectedIndex();
        
        
        if(indice > 2 && ind_aux < 3) {
            ind_aux = indice;
            anulaSeleccionArchivo();
        }
        else {
            if(ind_aux > 2) {
                activaSeleccionArchivo();
                ind_aux = cmbTramite.getSelectedIndex();
            } 
        }
    }//GEN-LAST:event_cmbTramiteActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtCptoNoGravadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCptoNoGravadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCptoNoGravadoActionPerformed

    private void optBloqueosLurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBloqueosLurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optBloqueosLurActionPerformed

    private void txtObservaciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservaciones2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservaciones2ActionPerformed

    private void btnLimpiaPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaPantallaActionPerformed
        limpiarPantalla();
    }//GEN-LAST:event_btnLimpiaPantallaActionPerformed

    private void txtPrecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecintoActionPerformed
        
    }//GEN-LAST:event_txtPrecintoActionPerformed

    private void txtPrecinto445ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecinto445ActionPerformed
      
    }//GEN-LAST:event_txtPrecinto445ActionPerformed

    private void txtPrecintoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecintoFocusLost
        txtPrecinto445.setText(txtPrecinto.getText());
        txtPrecintoLur.setText(txtPrecinto.getText());
        txtActa.requestFocus();
    }//GEN-LAST:event_txtPrecintoFocusLost

    private void txtCuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuitActionPerformed

    private void txtRazonSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazonSocialFocusLost
        completaNombre();
    }//GEN-LAST:event_txtRazonSocialFocusLost

    private void txtCuitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuitFocusLost
        System.out.println("En focus doc");
        completaDocumento();
    }//GEN-LAST:event_txtCuitFocusLost

    private void cmbOperadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbOperadorFocusLost
        if(ind_aux > 2) { txtCuit.requestFocus();}
    }//GEN-LAST:event_cmbOperadorFocusLost

    private void optUltimoZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optUltimoZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optUltimoZActionPerformed

    private void optOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optOperativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optOperativoActionPerformed

    private void txtZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws javax.persistence.PersistenceException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeerControladorFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeerControladorFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeerControladorFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeerControladorFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        lcf = new LeerControladorFiscal();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lcf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegirArchivo;
    private javax.swing.JButton btnLeerArchivo;
    private javax.swing.JButton btnLimpiaPantalla;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JComboBox<String> cmbCaracter;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbOperador;
    private javax.swing.JComboBox<String> cmbTramite;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCptosNoGravados;
    private javax.swing.JLabel lblInterAfip;
    private javax.swing.JLabel lblInterTec;
    private javax.swing.JLabel lblIvaDiario;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblOperador;
    private javax.swing.JLabel lblPagTec;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUltimoB;
    private javax.swing.JLabel lblVentaDiaria;
    private javax.swing.JLabel lblZ;
    private javax.swing.JLabel lvlObservaciones1;
    private javax.swing.JLabel lvlPaginaAfip;
    private javax.swing.JCheckBox optBloqueo;
    private javax.swing.JCheckBox optBloqueosLur;
    private javax.swing.JCheckBox optCompAuditoria;
    private javax.swing.JCheckBox optExtDatos;
    private javax.swing.JCheckBox optFecha;
    private javax.swing.JCheckBox optIntervinoLur;
    private javax.swing.JCheckBox optLogo;
    private javax.swing.JCheckBox optOperativo;
    private javax.swing.JCheckBox optSerie;
    private javax.swing.JCheckBox optTktBloqueo;
    private javax.swing.JCheckBox optUltimoZ;
    private javax.swing.JSeparator sprTitulo;
    private javax.swing.JTextField txtActa;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtBloqueos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCptoNoGravado;
    private javax.swing.JTextField txtCredencial;
    private javax.swing.JTextField txtCuit;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtInterAfip;
    private javax.swing.JTextField txtInterTec;
    private javax.swing.JTextField txtIvaDiario;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtObservaciones1;
    private javax.swing.JTextField txtObservaciones2;
    private javax.swing.JTextField txtPagTec;
    private javax.swing.JTextField txtPaginaAfip;
    private javax.swing.JTextField txtPrecinto;
    private javax.swing.JTextField txtPrecinto445;
    private javax.swing.JTextField txtPrecintoLur;
    private javax.swing.JTextField txtPuestoVta;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtSolicitud;
    private javax.swing.JTextField txtTecnico;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUltimoA;
    private javax.swing.JTextField txtUltimoB;
    private javax.swing.JTextField txtVentaDiaria;
    private javax.swing.JTextField txtZ;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtCuit() {
        return txtCuit;
    }

    public void setTxtCuit(String _cuit) {
        txtCuit.setText(_cuit);
    }

    public JTextField getTxtLegajo() {
        return txtLegajo;
    }

    public void setTxtLegajo(String _legajo) {
        txtLegajo.setText(_legajo);
    }

    public JTextField getTxtRazonSocial() {
        return txtRazonSocial;
    }

    //public void setTxtRazonSocial(JTextField txtRazonSocial) {
    public void setTxtRazonSocial(String txtRazonSocial) {
        System.out.println("En Razon Social");
        txtRazonSocial = txtRazonSocial;
    }

    private void completarPantalla() {
        LOGGER.log(Level.INFO, "Completando pantalla");
         LoaderDeInicio ldi = new LoaderDeInicio();
        
         /**
          * Para cargar el combo de agentes
          */
         listaAgentes = ldi.getOperadores();
         Agentes agte = new Agentes();
                  
         for (int i=0; i < listaAgentes.size(); i++) {
             agte = (Agentes) listaAgentes.get(i);
             cmbOperador.addItem(agte.getNombre());
         }
         
         /**
          * Para cargar el combo de 
          */
         
         List listaCaracter = ldi.getCaracter();
         ParCaracter caracter = new ParCaracter();
         
         for(int j=0; j < listaCaracter.size(); j++) {
             caracter = (ParCaracter) listaCaracter.get(j);
             cmbCaracter.addItem(caracter.getCaracter());
         }
         
         List listaTramites = ldi.getTramites();
         Tramites tramite = new Tramites();
         
         for(int k=0; k < listaTramites.size(); k++) {
             tramite = (Tramites) listaTramites.get(k);
             cmbTramite.addItem(tramite.getTramite());
         }
    }

    /**
     * Manda a generar las actas con los datos del caso procesado
     */
    private void generarActas() {
        Calendar cal = Calendar.getInstance();
        int anio= cal.get(Calendar.YEAR);
        LOGGER.log(Level.INFO, "Envia a generar archivos");
        ImprimeActaAnexoCF iacf = new ImprimeActaAnexoCF();
        iacf.imprime(controlador, anio);
    }
    
    

    /**
     * Recibe un objeto del tipo ControladorFiscal y lo persiste en la BD
     * @param controlador 
     */
    
    private void grabarTramite(ControladorFiscal controlador) {
        LOGGER.log(Level.INFO, "Grabar Tramite");
        Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.INFO, "Por Grabar","PEPEPE");
        int opcion;
            try {
                opcion = JOptionPane.showConfirmDialog(null, "¿Realmente deseas Grabar el caso?", "PersisteCF?", JOptionPane.YES_NO_OPTION);

                if (opcion == 0) { 
                  ControladorFiscalJpaController cfc = new ControladorFiscalJpaController(EntityMan.getInstance());
                  cfc.create(controlador);
                  generarActas();
                } else {
                   Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.INFO, "Decidio no grabar","PEPEPE");
                }


            } catch (Exception ex) {
                System.out.println("Es:" +controlador.getActa() +" - "  +
                                    controlador.getAgente() +" - "  +
                                    controlador.getCaracter()  +" - "  +
                                    controlador.getCodigo() +" - "  +
                                    controlador.getCredencial() +" - "  +
                                    controlador.getDireccion() +" - "  +
                                    controlador.getDocumento() +" - "  +
                                    controlador.getEstado() +" - "  +
                                    controlador.getFechaFinal()+" - "  +
                                    controlador.getFechaInicial() +" - "  +
                                    controlador.getFechaPoceso() +" - "  +
                                    controlador.getFecha() +" - "  +
                                    controlador.getLegajo()+" - "  +
                                    controlador.getMarca()+" - "  +
                                    controlador.getModelo()+" - "  +
                                    controlador.getNombre()+" - "  +
                                    controlador.getNumeroCodigo()+" - "  +
                                    controlador.getPaginaAfip()+" - "  +
                                    controlador.getPaginaTecnico()+" - "  +
                                    controlador.getPrecinto()+" - "  +
                                    controlador.getPrecinto445()+" - "  +
                                    controlador.getPrecintolur()+" - "  +
                                    controlador.getRazonSocial()+" - "  +
                                    controlador.getTramite()+" - "  +
                                    controlador.getBloqueo()+" - "  +
                                    controlador.getBloqueo()+" - "  +
                                    controlador.getBloqueos());
                
                
                
                
                
                
                
                LOGGER.log(Level.INFO, "No pudo grabar la Sol: " +controlador.getSolicitud() +"de: " +controlador.getRazonSocial());
                Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No pudo grabar la Sol: " +controlador.getSolicitud() +"de: " +controlador.getRazonSocial() +ex.getMessage());
            }
    }

    /**
     * Genera el objeto que luego será persistido en la BD
     * @return ControladorFiscal
     */
    
    private ControladorFiscal generaObjetoCF() throws ValidacionObjetoException {
        
        Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.INFO, "Preparando el objeto CF","PEPEPE");
        LOGGER.log(Level.INFO, "Antes de validar en genera objeto");
        
        
     //   try {
            if(valido()) {
                System.out.println("ES VALIDO!!!");
                LOGGER.log(Level.INFO, "Es Válido");
                
                Calendar cal = Calendar.getInstance();
                int fp_anio= cal.get(Calendar.YEAR);
                int fp_mes= cal.get(Calendar.MONTH);
                int fp_dia= cal.get(Calendar.DATE);
                
                String fp = String.valueOf(fp_anio)+String.format("%02d", fp_mes)+String.format("%02d", fp_dia);
                
                controlador.setTramite((String)cmbTramite.getSelectedItem());
                controlador.setSolicitud(Double.parseDouble(txtSolicitud.getText()));
                controlador.setAgente((String)cmbOperador.getSelectedItem());
                controlador.setLegajo(txtLegajo.getText());
                controlador.setTotalDiaria(Double.parseDouble(txtVentaDiaria.getText()));
                controlador.setTotalIvaDiario(Double.parseDouble(txtIvaDiario.getText()));
                controlador.setNoGravados(Double.parseDouble(txtCptoNoGravado.getText()));
                
                /**
                 * el índice menor que 3 se trata de trámites normales
                 * Si es 3 o mayor se trata de controladores con apertura por parte
                 * de técnico autorizado que emite otro tipo de acta y no genera
                 * el anexo IV
                 */
                if(cmbTramite.getSelectedIndex() < 3) {
                    controlador.setCompZ(Integer.parseInt(txtZ.getText()));

                    /**
                     * Estos 3 que siguen son los que se leen del archivo
                     */
                    
                    controlador.setVentaingresado(leyendo.getImporteTotal());
                    controlador.setIvaingresado(leyendo.getImporteIva());
                    controlador.setNogravadoingresado(Double.parseDouble(txtCptoNoGravado.getText()));
                    
                    //controlador.setUltimocingresado(Integer.parseInt(txtUltimoB.getText()));
                    //controlador.setUltimoaingresado(Integer.parseInt(txtUltimoA.getText()));
                    controlador.setUltimocingresado(leyendo.getUltimoB());
                    controlador.setUltimoaingresado(leyendo.getUltimoA());

                    if(optOperativo.isSelected()) { controlador.setOperativo(1);} 
                    else {controlador.setOperativo(0); }
                    
                    if(optUltimoZ.isSelected()) { controlador.setTieneultimoZ(1);} 
                    else {controlador.setTieneultimoZ(0); }
                    
                    if(optLogo.isSelected()) { controlador.setLogo(1);} 
                    else {controlador.setLogo(0); }

                    if(optSerie.isSelected()) { controlador.setSerie(1);} 
                    else {controlador.setSerie(0); }
                    

                    if(optBloqueosLur.isSelected()) { controlador.setCoincidebloqueo(1);} 
                    else {controlador.setCoincidebloqueo(0); }

                    if(optFecha.isSelected() ) { controlador.setFecha(1);}
                    else {controlador.setFecha(0);}

                    /* Falta el de extraccion de datos */

                    if(optCompAuditoria.isSelected()) { controlador.setCompaudit(1);}
                    else { controlador.setCompaudit(0);}

                    if(optBloqueo.isSelected()) { controlador.setBloqueo(1);}
                    else { controlador.setBloqueo(0);}

                    if(optIntervinoLur.isSelected()) { controlador.setInterlur(1);}
                    else { controlador.setInterlur(1); }

                    if(optBloqueosLur.isSelected()) { controlador.setCoincidebloqueo(1);}
                    else { controlador.setCoincidebloqueo(0);}

                    /** Cantidad de Intervenciones de AFIP */


                    /** Datos que se toman de la lectura del CF y que no se muestran en pantalla 
                     * por ahora
                     */
                    controlador.setFechaFinal(fst.fecha2SqliteFecha(leyendo.getFecha_fin()));
                    controlador.setFechaInicial(fst.fecha2SqliteFecha(leyendo.getFecha_inicio()));
                    controlador.setFechaPoceso(fst.fecha2SqliteFecha(leyendo.getFecha_extraccion()));
                    controlador.setZDesde(leyendo.getCompIni());
                    controlador.setZHasta(leyendo.getCompFinal());
                    controlador.setCuit(Double.parseDouble(leyendo.getCuit()));

                } else {
                    controlador.setTecnico(txtTecnico.getText());
                    controlador.setCredencial(txtCredencial.getText());
                    controlador.setObservaciones2(txtObservaciones2.getText());
                    controlador.setCuit(Double.parseDouble(txtCuit.getText()));
                    controlador.setFechaPoceso(fst.fecha2SqliteFecha(fp));
                }
                //controlador.setCuit(Double.parseDouble(leyendo.getCuit()));
                //System.out.println("Seteando: " +leyendo.getCuit());
                //controlador.setCuit(Double.parseDouble(fst.cuitSinGuiones(txtCuit.getText())));
                controlador.setRazonSocial(txtRazonSocial.getText());
                controlador.setNombre(txtNombre.getText());
                controlador.setDocumento(txtDocumento.getText());
                controlador.setTelefono(txtTelefono.getText());
                controlador.setCaracter((String)cmbCaracter.getSelectedItem()); 
                controlador.setDireccion(txtDireccion.getText());

                controlador.setMarca(txtMarca.getText());
                controlador.setModelo(txtModelo.getText());
                controlador.setCodigo(txtCodigo.getText());  
                controlador.setNumeroCodigo(txtNumero.getText());
                controlador.setPuestoVenta(Integer.parseInt(txtPuestoVta.getText()));
                //controlador.setBloqueos(Integer.parseInt(txtBloqueos.getText()));
                controlador.setBloqueos(leyendo.getBloqueo());
                controlador.setIntervenAfip(Integer.parseInt(txtInterAfip.getText()));
                /** Página donde se intervino */
                controlador.setPaginaAfip(txtPaginaAfip.getText());
                controlador.setIntervenTecnico(Integer.parseInt(txtInterTec.getText()));
                controlador.setPaginaTecnico(txtPagTec.getText());
                controlador.setEstado((String)cmbEstado.getSelectedItem());
                controlador.setPrecinto(txtPrecinto.getText());
                controlador.setPrecinto445(txtPrecinto445.getText());
                controlador.setPrecintolur(txtPrecintoLur.getText());
                controlador.setActa(txtActa.getText());
                controlador.setObservaciones1(txtObservaciones1.getText());
            }
            else {
                throw new ValidacionObjetoException("Errores de Validacion del Objeto CONTROLADOR");
            }
        /*} catch (ValidacionObjetoException ex) { 
            System.out.println("Debe mostrar el mensaje2!!");
            JOptionPane.showMessageDialog(this, "Error al crear el objeto: " );
        } */          
                    
        
        return controlador;
    }

/** Obtiene todos los componentes del contenedor JPanel y de acuerdo a que 
 * tipo sea, lo envia a un método especifico para que lo deje en el estado
 * del inicio de la pantalla
 * 
 */

    private void limpiarPantalla() {
        LOGGER.log(Level.INFO, "Limpia Pantalla!");
        //Component[] componentes = lcf.getContentPane().getComponents(); 
        
        Component[] componentes = this.getContentPane().getComponents();
        
        LOGGER.log(Level.INFO,"Cantidad de componentes: " +componentes.length );

        if(ind_aux > 2) { activaSeleccionArchivo(); }
                
        for(int i=0; componentes.length > i; i++) {
            //LOGGER.log(Level.INFO, "Componente es:" +componentes[i].getClass().getName());
            //System.out.println("Tengo a: " +componentes[i].getClass().getName());
            switch (componentes[i].getClass().getName()) {
                case "javax.swing.JTextField":
                    limpiaJtext((JTextField)componentes[i]);
                    break;
                case "javax.swing.JComboBox":
                    limpiaCombo((JComboBox)componentes[i]);
                    break;
                case "javax.swing.JCheckBox":
                    limpiaCheck((JCheckBox)componentes[i]);
                    break;
                default:
                    break;
            }
        }
    }

    private void limpiaJtext(JTextField campo) {
        //LOGGER.log(Level.INFO, "Limpia Jtext");
        campo.setText(null);
    }

    private void limpiaCombo(JComboBox combo) {
        //LOGGER.log(Level.INFO, "Limpia Combos");
        combo.setSelectedIndex(0);
    }

    private void limpiaCheck(JCheckBox check) {
        //LOGGER.log(Level.INFO, "Limpia Checks");
        check.setSelected(true);
    }

    private boolean valido() {
        LOGGER.log(Level.INFO, "Validando...");
        Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.INFO, "En Valido","PEPEPE");

        validarCampos();
        if(errores.size() == 0) {
            Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.INFO, "En Else empty","PEPEPE");
            return true;
        }
        else {
            Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.INFO, "En Empty retorno false","PEPEPE");
            return false;
        }
    }

    private void validarCampos() {
        Logger.getLogger(LeerControladorFiscal.class.getName()).log(Level.INFO, "En Validar","PEPEPE");
        LOGGER.log(Level.INFO, "Validando Campos");
       
        errores.clear();
        int indice = cmbTramite.getSelectedIndex();
        
        if(indice == 0){
            errores.add("Debe seleccionar un TRÁMITE");
        } else if ( indice > 0 && indice < 3) 
          {
                if(txtZ.getText().isEmpty()) {errores.add("Debe ingresar el N° del Cbte Z aportado");}
                if(txtVentaDiaria.getText().isEmpty()) {errores.add("Debe ingresar el importe de la VENTA DIARIA del cbte Z");}
                if(txtIvaDiario.getText().isEmpty()) {errores.add("Debe ingresar el importe del IVA DIARIO del cbte Z");}
                if(txtCptoNoGravado.getText().isEmpty()) {errores.add("Debe ingresar el importe del los CPTOS NO GRAVADOS del cbte Z");}
                if(txtUltimoB.getText().isEmpty()) {errores.add("Debe ingresar el ÚLTIMO CBTE B/C informado en el Z");}
                if(txtUltimoA.getText().isEmpty()) {errores.add("Debe ingresar el ÚLTIMO CBTE A informado en el Z");}
            } else {
                    if(txtCuit.getText().isEmpty()) { errores.add("Debe ingresar el CUIT del Ciudadano");}
                    if(txtRazonSocial.getText().isEmpty()) { errores.add("Debe ingresar la Razón Social del Ciudadano");}
                    if(txtNombre.getText().isEmpty()) { errores.add("Debe ingresar el NOMBRE completo del Ciudadano");}
                    if(txtDocumento.getText().isEmpty()) { errores.add("Debe ingresar Documento del Ciudadano");}
                    if(txtCodigo.getText().isEmpty()) { errores.add("Debe ingresar el CÓDIGO del CF");}
                    if(txtNumero.getText().isEmpty()) { errores.add("Debe ingresar NUMERO  del CF");}
                    if(txtPuestoVta.getText().isEmpty()) { errores.add("Debe ingresar el PUESTO DE VENTA del CF");}
                    if(txtBloqueos.getText().isEmpty()) { errores.add("Debe ingresar la cantidad de BLOQUEOS del CF");}
                    if(txtTecnico.getText().isEmpty()) {errores.add("Debe ingresar el NOMBRE COMPLETO DEL TÉCNICO");}
                    if(txtCredencial.getText().isEmpty()) {errores.add("Debe ingresar LA CREDENCIAL DEL TÉCNICO");}
               }
            
            if(txtSolicitud.getText().isEmpty()) {errores.add("Debe ingresar el nro de SOLICITUD");}

            indice = cmbOperador.getSelectedIndex();
            if(indice == 0){errores.add("Debe seleccionar un OPERADOR");}

            indice = cmbCaracter.getSelectedIndex();
            if(indice == 0){errores.add("Debe seleccionar un CARACTER de trámite");}
            
            if(txtDireccion.getText().isEmpty()) {errores.add("Debe ingresar una DIRECCIÓN");}
            if(txtMarca.getText().isEmpty()) {errores.add("Debe ingresar la MARCA del CF");}
            if(txtModelo.getText().isEmpty()) {errores.add("Debe ingresar el MODELO del CF");}
            if(txtInterAfip.getText().isEmpty()) {errores.add("Debe ingresar la cantidad de INTERVENCIONES AFIP");}
            if(txtPaginaAfip.getText().isEmpty()) {errores.add("Debe ingresar la PAGINA intervenida por agente AFIP");}
            if(txtInterTec.getText().isEmpty()) {errores.add("Debe ingresar la cantidad de intervenciones por técnicos");}
            if(txtPagTec.getText().isEmpty()) {errores.add("Debe ingresar la PAGINA con la última interv. del técnico");}
            if(txtPrecinto.getText().isEmpty()) {errores.add("Debe ingresar el N° del PRECINTO del CF");}
            if(txtPrecinto445.getText().isEmpty()) {errores.add("Debe ingresar el N° del PRECINTO que figura en el F445");}
            if(txtPrecintoLur.getText().isEmpty()) {errores.add("Debe ingresar el N° del PRECINTO que figura en el LUR");}
            if(txtActa.getText().isEmpty()) {errores.add("Debe ingresar el N° del ACTA");}
    }

    private String mensajesDeError() {
        String erroresDeValidacion = "\n";
        for(int i = 0; errores.size() > i; i++) {
            erroresDeValidacion = erroresDeValidacion+"- "+errores.get(i)+"\n";
        }
        return erroresDeValidacion;
    }

    private void anulaSeleccionArchivo() {
            
            txtCuit.setEditable(true);
            txtCuit.setBackground(Color.WHITE);
            txtRazonSocial.setEditable(true);
            txtRazonSocial.setBackground(Color.WHITE);
            txtCodigo.setEditable(true);
            txtCodigo.setBackground(Color.WHITE);
            txtNumero.setEditable(true);
            txtNumero.setBackground(Color.WHITE);
            txtPuestoVta.setEditable(true);
            txtPuestoVta.setBackground(Color.WHITE);
            txtBloqueos.setEditable(true);
            txtBloqueos.setBackground(Color.WHITE);
            optExtDatos.setEnabled(false);
            optCompAuditoria.setEnabled(false);
            optTktBloqueo.setEnabled(false);
            
            btnElegirArchivo.setEnabled(false);
            txtArchivo.setEditable(false);
            btnLeerArchivo.setEnabled(false);
    }

    private void activaSeleccionArchivo() {
            
        LOGGER.log(Level.INFO, "Activa Seleccion Archivo");
        
            txtCuit.setEditable(false);
            txtCuit.setBackground(Color.GRAY);
            txtRazonSocial.setEditable(false);
            txtRazonSocial.setBackground(Color.GRAY);
            txtCodigo.setEditable(false);
            txtCodigo.setBackground(Color.GRAY);
            txtNumero.setEditable(false);
            txtNumero.setBackground(Color.GRAY);
            txtPuestoVta.setEditable(false);
            txtPuestoVta.setBackground(Color.GRAY);
            txtBloqueos.setEditable(false);
            txtBloqueos.setBackground(Color.GRAY);
            
            btnElegirArchivo.setEnabled(true);
            txtArchivo.setEditable(true);
            btnLeerArchivo.setEnabled(true);
    }

    private void completaNombre() {
        LOGGER.log(Level.INFO, "Completa Nombre");
        if(ind_aux > 2) { txtNombre.setText(txtRazonSocial.getText());} 
        else {txtNombre.setText(leyendo.getRazon_social());}
        
        txtNombre.setBackground(Color.YELLOW);
        txtNombre.setToolTipText("Verifique que el Nombre propuesto sea el correcto");        
    }

    private void completaDocumento() {
        LOGGER.log(Level.INFO, "Completa Doc");
        if(ind_aux > 2) {
            if(!txtCuit.getText().isEmpty()) {
                FormateaSalidasTexto fst = new FormateaSalidasTexto();
                txtDocumento.setText(fst.cuitADocumento(txtCuit.getText()));
            }
        } else { txtDocumento.setText(leyendo.getDocumento());}
        
        txtDocumento.setBackground(Color.YELLOW);
        txtDocumento.setToolTipText("Verifique que el DNI propuesto sea el correcto");
    }
    
    

}